=== euCanSHare/vre/tool_schemas/tool_specification/tool_schema.json
{
  "id": "https://vre.eucanshare.bsc.es/tool-schema",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Tool definition schema",
  "description": "Specification of a openVRE Tool",
  "properties": {
    "_id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "default": "null"
    },
    "short_description": {
      "type": "string",
      "default": "null"
    },
    "long_description": {
      "type": "string",
      "default": "null"
    },
    "url": {
      "type": "string"
    },
    "publication": {
      "type": "string"
    },
    "owner": {
      "type": "object",
      "properties": {
        "institution": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "contact": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "author",
        "institution",
        "contact"
      ],
      "additionalProperties": false
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "imaging",
          "omics",
          "phenotypic",
	  "epidemiology",
          "other"
        ]
      },
      "default": "other"
    },
    "keywords_tool": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": "other"
    },
    "infrastructure": {
      "type": "object",
      "properties": {
        "executable": {
          "type": "string"
        },
        "cpus": {
          "type": "integer",
          "minimum": 1,
          "maximum": 12,
          "default": 1
        },
        "memory": {
          "type": "number",
          "minimum": 0,
          "maximum": 24,
          "default": 0
        },
        "wallTime": {
          "type": "integer",
          "minimum": 5,
          "maximum": 1440,
          "default": 1440
        },
        "clouds": {
          "type": "object",
          "properties": {
            "BSC_Starlife": {
              "$ref": "#/definitions/cloud"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "has_custom_viewer": {
      "type": "boolean",
      "default": true
    },
    "input_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "file_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "null",
                "AMB",
                "ANN",
                "BAI",
                "BAM",
                "BB",
                "BED",
                "BEDGRAPH",
                "BT2",
                "BW",
                "BWT",
                "CPT",
                "CSV",
                "DCD",
                "FASTA",
                "FASTQ",
                "GEM",
                "GFF",
                "GFF3",
                "GTF",
                "HDF5",
                "IDX",
                "JSON",
                "LIF",
                "MDCRD",
                "NETCDF",
                "NIFTI",
                "DICOM",
                "BIM",
                "FAM",
                "FRQ",
                "RAW",
                "NOSEX",
                "PAC",
                "PARMTOP",
                "PDB",
                "PDF",
                "PICKLE",
                "PNG",
                "RDATA",
                "RST",
                "SA",
                "TAR",
                "TBI",
                "TIFF",
                "TOP",
                "TPR",
                "TSV",
                "TXT",
                "VCF",
                "WIG",
                  "XLSX",
                "XTC"
              ]
            }
          },
          "data_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
		"tool_statistics",
		"dna_sequence",
		"data_atac_seq",
		"data_rna_seq",
		"sequence_rna",
		"data_chic",
		"configuration_file",
		"sequence_annotation",
		"bioimage",
		"image_mask",
		"deep_learning_model",
		"parameter_file",
		"report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
		"genome_annotation",
                "component_file",
		"machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"
              ]
            }
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "required": [
          "name",
          "description",
          "file_type",
          "data_type",
          "required",
          "allow_multiple"
        ]
      }
    },
    "input_files_public_dir": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "type": {
            "type": "string",
            "enum": [
              "integer",
              "number",
              "string",
              "enum",
              "enum_multiple",
              "boolean",
              "hidden"
            ]
          },
          "default": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "value": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "enum_items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "array"
              },
              "description": {
                "type": "array"
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "file_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "null",
                "AMB",
                "ANN",
                "BAI",
                "BAM",
                "BB",
                "BED",
                "BEDGRAPH",
                "BT2",
                "BW",
                "BWT",
                "CPT",
                "CSV",
                "DCD",
                "FASTA",
                "FASTQ",
                "GEM",
                "GFF",
                "GFF3",
                "GTF",
                "HDF5",
                "IDX",
                "JSON",
                "LIF",
                "MDCRD",
                "NETCDF",
                "NIFTI",
                "DICOM",
                "BIM",
                "FAM",
                "FRQ",
                "RAW",
                "NOSEX",
                "PAC",
                "PARMTOP",
                "PDB",
                "PDF",
                "PICKLE",
                "PNG",
                "RDATA",
                "RST",
                "SA",
                "TAR",
                "TBI",
                "TIFF",
                "TOP",
                "TPR",
                "TSV",
                "TXT",
                "VCF",
                "WIG",
                  "XLSX",
                "XTC"
              ]
            }
          },
          "data_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
		"tool_statistics",
                "dna_sequence",
                "data_atac_seq",
                "data_rna_seq",
                "sequence_rna",
                "data_chic",
                "configuration_file",
                "sequence_annotation",
                "bioimage",
                "image_mask",
                "deep_learning_model",
                "parameter_file",
                "report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
                "component_file",
                "machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"

              ]
            }
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "additionalProperties": false
      }
    },
    "input_files_combinations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "input_files": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "description",
          "input_files"
        ]
      }
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "type": {
            "type": "string",
            "enum": [
              "integer",
              "number",
              "string",
              "enum",
              "enum_multiple",
              "boolean",
              "hidden"
            ]
          },
          "default": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "value": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "enum_items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "array"
              },
              "description": {
                "type": "array"
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "maximum": {
            "type": "integer"
          },
          "minimum": {
            "type": "integer"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "description",
          "type"
        ]
      }
    },
    "output_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          },
          "file": {
            "type": "object",
            "properties": {
              "file_type": {
                "type": "string",
                "enum": [
                  "null",
                  "AMB",
                  "ANN",
                  "BAI",
                  "BAM",
                  "BB",
                  "BED",
                  "BEDGRAPH",
                  "BT2",
                  "BW",
                  "BWT",
                  "CPT",
                  "CSV",
                  "DCD",
                  "FASTA",
                  "FASTQ",
                  "GEM",
                  "GFF",
                  "GFF3",
                  "GTF",
                  "HDF5",
                  "IDX",
                  "JSON",
                  "LIF",
                  "MDCRD",
                  "NETCDF",
                  "NIFTI",
                  "DICOM",
                  "BIM",
                  "FAM",
                  "FRQ",
                  "RAW",
                  "NOSEX",
                  "PAC",
                  "PARMTOP",
                  "PDB",
                  "PDF",
                  "PICKLE",
                  "PNG",
                  "RDATA",
                  "RST",
                  "SA",
                  "TAR",
                  "TBI",
                  "TIFF",
                  "TOP",
                  "TPR",
                  "TSV",
                  "TXT",
                  "VCF",
                  "WIG",
                  "XLSX",
                  "XTC"
                ]
              },
              "data_type": {
                "type": "string",
                "enum": [
                "tool_statistics",
                "dna_sequence",
                "data_atac_seq",
                "data_rna_seq",
                "sequence_rna",
                "data_chic",
                "configuration_file",
                "sequence_annotation",
                "bioimage",
                "image_mask",
                "deep_learning_model",
                "parameter_file",
                "report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
		"genome_annotation",
                "component_file",
                "machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"
                ]
              },
              "file_path": {
                "type": "string"
              },
              "compressed": {
                "type": "string",
                "enum": [
                  "null",
                  "gzip",
                  "zip"
                ]
              },
              "taxon_id": {
                "type": "integer"
              },
              "source_id": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "meta_data": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "tool": {
                    "type": "string"
                  },
                  "assembly": {
                    "type": "string"
                  },
                  "visible": {
                    "type": "boolean",
                    "default": true
                  }
                },
                "required": [
                  "description",
                  "visible"
                ]
              }
            },
            "required": [
              "file_type",
              "data_type",
              "meta_data"
            ]
          }
        },
        "required": [
          "name",
          "required",
          "allow_multiple",
          "file"
        ]
      }
    }
  },
  "required": [
    "_id",
    "name",
    "short_description",
    "long_description",
    "title",
    "owner",
    "keywords",
    "keywords_tool",
    "infrastructure",
    "input_files",
    "input_files_public_dir",
    "arguments",
    "output_files"
  ],
  "additionalProperties": false,
  "definitions": {
    "cloud": {
      "oneOf": [
        {
          "$ref": "#/definitions/SGE"
        },
        {
          "$ref": "#/definitions/PMES"
        }
      ]
    },
    "SGE": {
      "type": "object",
      "properties": {
        "launcher": {
          "type": "string",
          "pattern": "^SGE$"
        },
        "default_cloud": {
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "launcher"
      ],
      "additionalProperties": false
    },
    "PMES": {
      "type": "object",
      "properties": {
        "launcher": {
          "type": "string",
          "pattern": "^PMES$"
        },
        "workflowType": {
          "type": "string",
          "enum": [
            "Single",
            "COMPSs"
          ],
          "default": "Single"
        },
        "default_cloud": {
          "type": "boolean",
          "default": false
        },
        "minimumVMs": {
          "type": "integer",
          "default": 1
        },
        "initialVMs": {
          "type": "integer",
          "default": 1
        }
      },
      "required": [
        "launcher"
      ],
      "additionalProperties": false
    }
  }
}

=== euCanSHare/vre/tool_schemas/tool_specification/examples/example_minimal.json
{
    "_id": "my_tool_id",
    "name": "My Tool",
    "title": "My tool Complete Name",
    "short_description": "This is a one or two lines description of what 'My Tool' does. You can leave a dummy text for the moment!",
    "long_description": "This is a longer description of what 'My Tool' does. It includes information about the software use for it, the supported inputs, the expected results, etc. You can leave a dummy text for the moment!",
    "url": "http://gitbub.com/MyTool",
    "publication":"00.0000/nar/gks000",
    "owner": {
        "author": "My Name",
        "institution": "My University",
        "contact": "myEmail@uni.cat",
        "url": "https://MyUniversity.uni.cat/MyGroup"
    },
    "keywords": [
      "imaging"
    ],
   "keywords_tool": [
      "whatever",
      "keyword"
    ],
    "infrastructure": {
        "memory": 12,
        "cpus": 4
    },
    "input_files": [
        {
            "name": "my_input_id1",
            "description": "My Input 1",
            "help": "Some explanation about 'My Input 1' displayed to user in help tooltips ",
            "file_type": [
                "NIFTI"
            ],
            "data_type": [
                "bioimage"
            ],
            "required": true,
            "allow_multiple": false
        },
        {
            "name": "my_input_id2",
            "description": "My Input 2",
            "help": "Some explanation about 'My Input 2' displayed to user in help tooltips ",
            "file_type": [
                "NIFTI"
            ],
            "data_type": [
                "bioimage"
            ],
            "required": true,
            "allow_multiple": false
        }
    ],
    "input_files_public_dir":[],
    "input_files_combinations": [
      {
        "description" : "Analyse a single FASTA",
        "input_files":[
            "my_input_id1"
        ]
      },{
        "description" : "Compare 2 FASTA files",
        "input_files":[
            "my_input_id1",
            "my_input_id2"
          ]
      }
    ],
    "arguments": [
    {
        "name": "argument_id1",
        "description": "Argument 1",
        "help": "Some explanation about 'Argument 1' displayed to user in help tooltips",
        "type": "integer",
        "default":"99"
    }
    ],
    "has_custom_viewer": true,
    "output_files": [
        {
            "name": "output_id1",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "NIFTI",
                "data_type": "image_mask",
                "meta_data": {
                    "visible": true,
                    "description": "Here goes a short description of what this output file contains"
                }
            }
        },
        {
            "name": "output_id2",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "TAR",
                "data_type": "tool_statistics",
                "file_path": "myExecutionStatistics.tar.gz",
                "compressed": "gzip",
                "meta_data": {
                    "visible": false,
                    "description": "Here goes a short description of what this output file contains"
                }
            }
        }
    ]
}
