=== euCanSHare/vre/tool_schemas/tool_specification/tool_schema_io.json
{
  "id": "https://vre.eucanshare.bsc.es/tool-schema",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Tool definition schema - I/O",
  "description": "Specification of inputs, outputs and arguments for a openVRE Tool",
  "properties": {
    "_id": {
      "type": "string"
    },
    "input_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "file_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "null",
                "AMB",
                "ANN",
                "BAI",
                "BAM",
                "BB",
                "BED",
                "BEDGRAPH",
                "BT2",
                "BW",
                "BWT",
                "CPT",
                "CSV",
                "DCD",
                "FASTA",
                "FASTQ",
                "GEM",
                "GFF",
                "GFF3",
                "GTF",
                "HDF5",
                "HTML",
                "IDX",
                "JSON",
                "LIF",
                "MDCRD",
                "NETCDF",
                "NIFTI",
                "DICOM",
                "BIM",
                "FAM",
                "FRQ",
                "RAW",
                "NOSEX",
                "PAC",
                "PARMTOP",
                "PDB",
                "PDF",
                "PICKLE",
                "PNG",
                "RDATA",
                "RST",
                "SA",
                "TAR",
                "TBI",
                "TIFF",
                "TOP",
                "TPR",
                "TSV",
                "TXT",
                "VCF",
                "WIG",
                "XLSX",
                "XTC"
              ]
            }
          },
          "data_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "tool_statistics",
                "dna_sequence",
                "data_atac_seq",
                "data_rna_seq",
                "sequence_rna",
                "data_chic",
                "configuration_file",
                "sequence_annotation",
                "bioimage",
                "image_mask",
                "deep_learning_model",
                "parameter_file",
                "report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
                "component_file",
                "machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"
              ]
            }
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "required": [
          "name",
          "description",
          "file_type",
          "data_type",
          "required",
          "allow_multiple"
        ]
      }
    },
    "input_files_public_dir": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "type": {
            "type": "string",
            "enum": [
              "integer",
              "number",
              "string",
              "enum",
              "enum_multiple",
              "boolean",
              "hidden"
            ]
          },
          "default": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "value": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "enum_items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "array"
              },
              "description": {
                "type": "array"
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "file_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "null",
                "AMB",
                "ANN",
                "BAI",
                "BAM",
                "BB",
                "BED",
                "BEDGRAPH",
                "BT2",
                "BW",
                "BWT",
                "CPT",
                "CSV",
                "DCD",
                "FASTA",
                "FASTQ",
                "GEM",
                "GFF",
                "GFF3",
                "GTF",
                "HDF5",
                "HTML",
                "IDX",
                "JSON",
                "LIF",
                "MDCRD",
                "NETCDF",
                "NIFTI",
                "DICOM",
                "BIM",
                "FAM",
                "FRQ",
                "RAW",
                "NOSEX",
                "PAC",
                "PARMTOP",
                "PDB",
                "PDF",
                "PICKLE",
                "PNG",
                "RDATA",
                "RST",
                "SA",
                "TAR",
                "TBI",
                "TIFF",
                "TOP",
                "TPR",
                "TSV",
                "TXT",
                "VCF",
                "WIG",
                  "XLSX",
                "XTC"
              ]
            }
          },
          "data_type": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "tool_statistics",
                "dna_sequence",
                "data_atac_seq",
                "data_rna_seq",
                "sequence_rna",
                "data_chic",
                "configuration_file",
                "sequence_annotation",
                "bioimage",
                "image_mask",
                "deep_learning_model",
                "parameter_file",
                "report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
		"genome_annotation",
                "component_file",
                "machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"
              ]
            }
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "additionalProperties": false
      }
    },
    "input_files_combinations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "input_files": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "description",
          "input_files"
        ]
      }
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "help": {
            "type": "string",
            "default": null
          },
          "type": {
            "type": "string",
            "enum": [
              "integer",
              "number",
              "string",
              "enum",
              "enum_multiple",
              "boolean",
              "hidden"
            ]
          },
          "default": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "value": {
            "type": ["integer", "string", "boolean", "number", "array"],
            "default": "null"
          },
          "enum_items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "array"
              },
              "description": {
                "type": "array"
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "maximum": {
            "type": "integer"
          },
          "minimum": {
            "type": "integer"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "description",
          "type"
        ]
      }
    },
    "output_files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "required": {
            "type": "boolean",
            "default": true
          },
          "allow_multiple": {
            "type": "boolean",
            "default": false
          },
          "file": {
            "type": "object",
            "properties": {
              "file_type": {
                "type": "string",
                "enum": [
                  "null",
                  "AMB",
                  "ANN",
                  "BAI",
                  "BAM",
                  "BB",
                  "BED",
                  "BEDGRAPH",
                  "BT2",
                  "BW",
                  "BWT",
                  "CPT",
                  "CSV",
                  "DCD",
                  "FASTA",
                  "FASTQ",
                  "GEM",
                  "GFF",
                  "GFF3",
                  "GTF",
                  "HDF5",
                  "HTML",
                  "IDX",
                  "JSON",
                  "LIF",
                  "MDCRD",
                  "NETCDF",
                  "NIFTI",
                  "DICOM",
                  "BIM",
                  "FAM",
                  "FRQ",
                  "RAW",
                  "NOSEX",
                  "PAC",
                  "PARMTOP",
                  "PDB",
                  "PDF",
                  "PICKLE",
                  "PNG",
                  "RDATA",
                  "RST",
                  "SA",
                  "TAR",
                  "TBI",
                  "TIFF",
                  "TOP",
                  "TPR",
                  "TSV",
                  "TXT",
                  "VCF",
                  "WIG",
                  "XLSX",
                  "XTC"
                ]
              },
              "data_type": {
                "type": "string",
                "enum": [
                "tool_statistics",
                "dna_sequence",
                "data_atac_seq",
                "data_rna_seq",
                "sequence_rna",
                "data_chic",
                "configuration_file",
                "sequence_annotation",
                "bioimage",
                "image_mask",
                "deep_learning_model",
                "parameter_file",
                "report",
                "extended_MAP_file",
                "sample_information_file",
                "allele_frequency_report",
		"genome_annotation",
                "component_file",
                "machine_learning_features",
                "expression_matrix",
                "annotations",
                "group_definitions",
                "covariate_matrix",
                "differential_matrix",
                "study_data",
                "study_meta_data"
		]
              },
              "file_path": {
                "type": "string"
              },
              "compressed": {
                "type": "string",
                "enum": [
                  "null",
                  "gzip",
                  "zip"
                ]
              },
              "taxon_id": {
                "type": "integer"
              },
              "source_id": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "meta_data": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "tool": {
                    "type": "string"
                  },
                  "assembly": {
                    "type": "string"
                  },
                  "visible": {
                    "type": "boolean",
                    "default": true
                  }
                },
                "required": [
                  "description",
                  "visible"
                ]
              }
            },
            "required": [
              "file_type",
              "data_type",
              "meta_data"
            ]
          }
        },
        "required": [
          "name",
          "required",
          "allow_multiple",
          "file"
        ]
      }
    }
  },
  "required": [
    "_id",
    "input_files",
    "input_files_public_dir",
    "arguments",
    "output_files"
  ],
  "additionalProperties": false
}

=== euCanSHare/vre/install/data/tool_schemas/tool_specification/examples/example_io.json
{
    "_id": "my_tool_id",
    "input_files": [
        {
            "name": "my_input_id1",
            "description": "My Input 1",
            "help": "Some explanation about 'My Input 1' displayed to user in help tooltips ",
            "file_type": [
                "NIFTI"
            ],
            "data_type": [
                "bioimage"
            ],
            "required": true,
            "allow_multiple": false
        },
        {
            "name": "my_input_id2",
            "description": "My Input 2",
            "help": "Some explanation about 'My Input 2' displayed to user in help tooltips ",
            "file_type": [
                "NIFTI"
            ],
            "data_type": [
                "bioimage"
            ],
            "required": true,
            "allow_multiple": false
        }
    ],
    "input_files_public_dir":[],
    "input_files_combinations": [
      {
        "description" : "Analyse a single FASTA",
        "input_files":[
            "my_input_id1"
        ]
      },{
        "description" : "Compare 2 FASTA files",
        "input_files":[
            "my_input_id1",
            "my_input_id2"
          ]
      }
    ],
    "arguments": [
    {
        "name": "argument_id1",
        "description": "Argument 1",
        "help": "Some explanation about 'Argument 1' displayed to user in help tooltips",
        "type": "integer",
        "default":"99"
    }
    ],
    "output_files": [
        {
            "name": "output_id1",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "NIFTI",
                "data_type": "image_mask",
                "meta_data": {
                    "visible": true,
                    "description": "Here goes a short description of what this output file contains"
                }
            }
        },
        {
            "name": "output_id2",
            "required": true,
            "allow_multiple": false,
            "file": {
                "file_type": "TAR",
                "data_type": "tool_statistics",
                "file_path": "myExecutionStatistics.tar.gz",
                "compressed": "gzip",
                "meta_data": {
                    "visible": false,
                    "description": "Here goes a short description of what this output file contains"
                }
            }
        }
    ]
}
